### ISSUE TITLE
error: invalid use of incomplete type ‘const bam_index_t {aka const struct __hts_idx_t}’

### ISSUE THREAD

**Issue by kumarsaurabh20** [kenchen/breakdancer#3]
Hi,
I have been trying to install breakdancer but came across this compilation error. Any suggestions? Here is the log:

`ks575@minerva:~/breakdancer-1.1.2/cpp$ make
g++ -g -Wall -O2 -I/home2/ISAD/ks575/software/samtools/samtools-1.3.1 BreakDancerMax.cpp AlnParser.cpp Poisson.cpp -o breakdancer-max -lm -lz -L/home2/ISAD/ks575/software/samtools/samtools-1.3.1 -lbam
In file included from /usr/include/c++/4.8/backward/strstream:51:0,
                 from BreakDancerMax.h:3,
                 from BreakDancerMax.cpp:1:
/usr/include/c++/4.8/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
In file included from BreakDancerMax.h:23:0,
                 from BreakDancerMax.cpp:1:
samtools.h: In function ‘int reg2bins(uint32_t, uint32_t, uint16_t*)’:
samtools.h:85:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (k =    1 + (beg>>26); k <=    1 + (end>>26); ++k) list[i++] = k;
                                                 ^
samtools.h:86:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (k =    9 + (beg>>23); k <=    9 + (end>>23); ++k) list[i++] = k;
                                                 ^
samtools.h:87:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (k =   73 + (beg>>20); k <=   73 + (end>>20); ++k) list[i++] = k;
                                                 ^
samtools.h:88:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (k =  585 + (beg>>17); k <=  585 + (end>>17); ++k) list[i++] = k;
                                                 ^
samtools.h:89:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (k = 4681 + (beg>>14); k <= 4681 + (end>>14); ++k) list[i++] = k;
                                                 ^
samtools.h: In function ‘pair64_t* get_chunk_coordinates(const bam_index_t*, int, int, int, int*)’:
samtools.h:105:13: error: invalid use of incomplete type ‘const bam_index_t {aka const struct __hts_idx_t}’
  index = idx->index[tid];
             ^
In file included from /home2/ISAD/ks575/software/samtools/samtools-1.3.1/htslib-1.3.1/htslib/sam.h:30:0,
                 from /home2/ISAD/ks575/software/samtools/samtools-1.3.1/sam.h:28,
                 from BreakDancerMax.h:17,
                 from BreakDancerMax.cpp:1:
/home2/ISAD/ks575/software/samtools/samtools-1.3.1/htslib-1.3.1/htslib/hts.h:417:8: error: forward declaration of ‘const bam_index_t {aka const struct __hts_idx_t}’
 struct __hts_idx_t;
        ^
In file included from BreakDancerMax.h:23:0,
                 from BreakDancerMax.cpp:1:
samtools.h:106:39: error: invalid use of incomplete type ‘const bam_index_t {aka const struct __hts_idx_t}’
  min_off = (beg>>BAM_LIDX_SHIFT >= idx->index2[tid].n)? 0 : idx->index2[tid].offset[beg>>BAM_LIDX_SHIFT];
                                       ^
In file included from /home2/ISAD/ks575/software/samtools/samtools-1.3.1/htslib-1.3.1/htslib/sam.h:30:0,
                 from /home2/ISAD/ks575/software/samtools/samtools-1.3.1/sam.h:28,
                 from BreakDancerMax.h:17,
                 from BreakDancerMax.cpp:1:
/home2/ISAD/ks575/software/samtools/samtools-1.3.1/htslib-1.3.1/htslib/hts.h:417:8: error: forward declaration of ‘const bam_index_t {aka const struct __hts_idx_t}’
 struct __hts_idx_t;
        ^
In file included from BreakDancerMax.h:23:0,
                 from BreakDancerMax.cpp:1:
samtools.h:106:64: error: invalid use of incomplete type ‘const bam_index_t {aka const struct __hts_idx_t}’
  min_off = (beg>>BAM_LIDX_SHIFT >= idx->index2[tid].n)? 0 : idx->index2[tid].offset[beg>>BAM_LIDX_SHIFT];
                                                                ^
In file included from /home2/ISAD/ks575/software/samtools/samtools-1.3.1/htslib-1.3.1/htslib/sam.h:30:0,
                 from /home2/ISAD/ks575/software/samtools/samtools-1.3.1/sam.h:28,
                 from BreakDancerMax.h:17,
                 from BreakDancerMax.cpp:1:
/home2/ISAD/ks575/software/samtools/samtools-1.3.1/htslib-1.3.1/htslib/hts.h:417:8: error: forward declaration of ‘const bam_index_t {aka const struct __hts_idx_t}’
 struct __hts_idx_t;
        ^
In file included from BreakDancerMax.h:23:0,
                 from BreakDancerMax.cpp:1:
samtools.h:119:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (j = 0; j < p->n; ++j)
                       ^
BreakDancerMax.cpp: In function ‘int ReadBamChr(bam1_t*, bamFile, int, int, int, uint64_t*, int*, int*, pair64_t*, int)’:
BreakDancerMax.cpp:2241:52: warning: ignoring return value of ‘int64_t bgzf_seek(BGZF*, int64_t, int)’, declared with attribute warn_unused_result [-Wunused-result]
                 bam_seek(fp, off[*i+1].u, SEEK_SET);
                                                    ^
AlnParser.cpp: In function ‘std::vector<std::basic_string<char> > AlnParser(bam1_t*, std::string, std::string, std::map<std::basic_string<char>, std::basic_string<char> >&, int, std::string)’:
AlnParser.cpp:22:6: warning: unused variable ‘a’ [-Wunused-variable]
  int a = 0;
      ^
AlnParser.cpp:112:42: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
       else if(b->core.mpos > b->core.pos && (ori.compare("-") == 0) || b->core.pos > b->core.mpos && (ori.compare("+") == 0))
                                          ^
make: *** [all] Error 1`

**Comment by jgibson2** [comment]
A bit late, but the workaround is this: use an earlier version of samtools. Compilation was done with version 0.1.6, but I got it to compile with v0.1.19. You will also (most likely) have to add -lpthread to your g++ command.
